version: "3.9"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  indexer:
    restart: "always"
    image: ${IMAGE_NAME}
    container_name: cosmos-indexer
    user: cosmos-indexer
    stop_grace_period: 10s
    env_file:
      - .env
    ports:
      - "9002:9002/tcp"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    links:
      - postgres
    networks:
      vpcbr-2:
        ipv4_address: 10.5.0.7
    <<: *logging
    command:
    - /bin/sh
    - -c
    - |
      cosmos-indexer index \
      --log.pretty = true \
      --log.level = info \
      --base.start-block 1386440 \
      --base.end-block -1 \
      --base.throttling 2.005 \
      --base.rpc-workers 1 \
      --base.index-transactions true \
      --base.index-block-events true \
      --probe.rpc https://celestia-rpc.publicnode.com:443  \
      --probe.account-prefix celestia \
      --probe.chain-id mocha-4 \
      --probe.chain-name celestia \
      --database.host postgres \
      --database.database db_name \
      --database.user taxuser \
      --database.password password \
      --server.port 9002 \
      --redis.addr redis:6379 \
      --mongo.addr mongodb://admin:password@mongodb:27017 \
      --mongo.db search_indexer

networks:
  vpcbr-2:
    external:
      name: vpcbr