version: "3.9"

services:
  postgres:
    restart: "unless-stopped"
    image: postgres:15-alpine
    stop_grace_period: 1m
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432/tcp
    healthcheck:
      test: ["CMD", "nc", "-z", "-v", "localhost", "5432"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      default:
        aliases:
          - cosmos-indexer

  indexer:
    restart: "no"
    build:
      dockerfile: Dockerfile
    user: cosmos-indexer
    stop_grace_period: 10s
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
    networks:
      default:
        aliases:
          - cosmos-indexer
    environment:
      - EXTENDED_ARGS=""
      - LOG_LEVEL="info"
    command:
    - /bin/sh
    - -c
    - |
      cosmos-indexer index \
      --log.pretty=${PRETTY_LOG} \
      --log.level=${LOG_LEVEL \
      --base.index-transactions=${INDEX_TRANSACTIONS} \
      --base.index-block-events=${INDEX_BLOCK_EVENTS} \
      --base.start-block=${START_BLOCK} \
      --base.end-block=-${END_BLOCK} \
      --base.throttling=${THROTTLING} \
      --base.rpc-workers=${RPC_WORKERS} \
      --base.reindex=${REINDEX} \
      --base.reattempt-failed-blocks=false \
      --probe.rpc=${RPC_URL} \
      --probe.account-prefix=${ACCOUNT_PREFIX} \
      --probe.chain-id=${CHAIN_ID} \
      --probe.chain-name=${CHAIN_NAME} \
      --database.host=postgres \
      --database.database=${POSTGRES_DB} \
      --database.user=${POSTGRES_USER} \
      --database.password=${POSTGRES_PASSWORD} \
      ${EXTENDED_ARGS}

volumes:
  postgres:
