version: "3.9"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  postgres:
    restart: "unless-stopped"
    image: postgres:15-alpine
    stop_grace_period: 1m
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=taxuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - "5437:5432/tcp"
    healthcheck:
      test: ["CMD", "nc", "-z", "-v", "localhost", "5432"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      vpcbr-2:
        ipv4_address: 10.5.0.8
    <<: *logging
  redis:
    image: redis
    ports:
      - '6381:6379'
    networks:
      vpcbr-2:
        ipv4_address: 10.5.0.10
    <<: *logging
  mongodb:
    image: mongo:5.0.2
    container_name: mongodb
    shm_size: 1g
    environment:
      - MONGO_INITDB_DATABASE=search_indexer
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - db:/data/db
    networks:
      vpcbr-2:
        ipv4_address: 10.5.0.21
    ports:
      - '27017-27019:27017-27019'
  indexer:
    restart: "always"
    build:
      context: .
      dockerfile: Dockerfile
    user: cosmos-indexer
    stop_grace_period: 10s
    ports:
      - "9002:9002/tcp"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
    networks:
      vpcbr-2:
        ipv4_address: 10.5.0.7
    <<: *logging
    command:
    - /bin/sh
    - -c
    - |
      cosmos-indexer index \
      --log.pretty = true \
      --log.level = info \
      --base.start-block 1386440 \
      --base.end-block -1 \
      --base.throttling 2.005 \
      --base.rpc-workers 1 \
      --base.index-transactions true \
      --base.index-block-events true \
      --probe.rpc https://celestia-rpc.publicnode.com:443  \
      --probe.account-prefix celestia \
      --probe.chain-id mocha-4 \
      --probe.chain-name celestia \
      --database.host postgres \
      --database.database postgres \
      --database.user taxuser \
      --database.password password \
      --server.port 9002 \
      --redis.addr redis:6379 \
      --mongo.addr mongodb://admin:password@mongodb:27017 \
      --mongo.db search_indexer

volumes:
  db:

networks:
  vpcbr-2:
    external:
      name: vpcbr