// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: blocks.proto

package blocks

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	BlocksService_BlockInfo_FullMethodName         = "/blocks.BlocksService/BlockInfo"
	BlocksService_BlockValidators_FullMethodName   = "/blocks.BlocksService/BlockValidators"
	BlocksService_TxChartByDay_FullMethodName      = "/blocks.BlocksService/TxChartByDay"
	BlocksService_TxByHash_FullMethodName          = "/blocks.BlocksService/TxByHash"
	BlocksService_TotalTransactions_FullMethodName = "/blocks.BlocksService/TotalTransactions"
)

// BlocksServiceClient is the client API for BlocksService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BlocksServiceClient interface {
	BlockInfo(ctx context.Context, in *GetBlockInfoRequest, opts ...grpc.CallOption) (*GetBlockInfoResponse, error)
	BlockValidators(ctx context.Context, in *GetBlockValidatorsRequest, opts ...grpc.CallOption) (*GetBlockValidatorsResponse, error)
	TxChartByDay(ctx context.Context, in *TxChartByDayRequest, opts ...grpc.CallOption) (*TxChartByDayResponse, error)
	TxByHash(ctx context.Context, in *TxByHashRequest, opts ...grpc.CallOption) (*TxByHashResponse, error)
	TotalTransactions(ctx context.Context, in *TotalTransactionsRequest, opts ...grpc.CallOption) (*TotalTransactionsResponse, error)
}

type blocksServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBlocksServiceClient(cc grpc.ClientConnInterface) BlocksServiceClient {
	return &blocksServiceClient{cc}
}

func (c *blocksServiceClient) BlockInfo(ctx context.Context, in *GetBlockInfoRequest, opts ...grpc.CallOption) (*GetBlockInfoResponse, error) {
	out := new(GetBlockInfoResponse)
	err := c.cc.Invoke(ctx, BlocksService_BlockInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blocksServiceClient) BlockValidators(ctx context.Context, in *GetBlockValidatorsRequest, opts ...grpc.CallOption) (*GetBlockValidatorsResponse, error) {
	out := new(GetBlockValidatorsResponse)
	err := c.cc.Invoke(ctx, BlocksService_BlockValidators_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blocksServiceClient) TxChartByDay(ctx context.Context, in *TxChartByDayRequest, opts ...grpc.CallOption) (*TxChartByDayResponse, error) {
	out := new(TxChartByDayResponse)
	err := c.cc.Invoke(ctx, BlocksService_TxChartByDay_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blocksServiceClient) TxByHash(ctx context.Context, in *TxByHashRequest, opts ...grpc.CallOption) (*TxByHashResponse, error) {
	out := new(TxByHashResponse)
	err := c.cc.Invoke(ctx, BlocksService_TxByHash_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blocksServiceClient) TotalTransactions(ctx context.Context, in *TotalTransactionsRequest, opts ...grpc.CallOption) (*TotalTransactionsResponse, error) {
	out := new(TotalTransactionsResponse)
	err := c.cc.Invoke(ctx, BlocksService_TotalTransactions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlocksServiceServer is the server API for BlocksService service.
// All implementations must embed UnimplementedBlocksServiceServer
// for forward compatibility
type BlocksServiceServer interface {
	BlockInfo(context.Context, *GetBlockInfoRequest) (*GetBlockInfoResponse, error)
	BlockValidators(context.Context, *GetBlockValidatorsRequest) (*GetBlockValidatorsResponse, error)
	TxChartByDay(context.Context, *TxChartByDayRequest) (*TxChartByDayResponse, error)
	TxByHash(context.Context, *TxByHashRequest) (*TxByHashResponse, error)
	TotalTransactions(context.Context, *TotalTransactionsRequest) (*TotalTransactionsResponse, error)
	mustEmbedUnimplementedBlocksServiceServer()
}

// UnimplementedBlocksServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBlocksServiceServer struct {
}

func (UnimplementedBlocksServiceServer) BlockInfo(context.Context, *GetBlockInfoRequest) (*GetBlockInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BlockInfo not implemented")
}
func (UnimplementedBlocksServiceServer) BlockValidators(context.Context, *GetBlockValidatorsRequest) (*GetBlockValidatorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BlockValidators not implemented")
}
func (UnimplementedBlocksServiceServer) TxChartByDay(context.Context, *TxChartByDayRequest) (*TxChartByDayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TxChartByDay not implemented")
}
func (UnimplementedBlocksServiceServer) TxByHash(context.Context, *TxByHashRequest) (*TxByHashResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TxByHash not implemented")
}
func (UnimplementedBlocksServiceServer) TotalTransactions(context.Context, *TotalTransactionsRequest) (*TotalTransactionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TotalTransactions not implemented")
}
func (UnimplementedBlocksServiceServer) mustEmbedUnimplementedBlocksServiceServer() {}

// UnsafeBlocksServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlocksServiceServer will
// result in compilation errors.
type UnsafeBlocksServiceServer interface {
	mustEmbedUnimplementedBlocksServiceServer()
}

func RegisterBlocksServiceServer(s grpc.ServiceRegistrar, srv BlocksServiceServer) {
	s.RegisterService(&BlocksService_ServiceDesc, srv)
}

func _BlocksService_BlockInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlocksServiceServer).BlockInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlocksService_BlockInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlocksServiceServer).BlockInfo(ctx, req.(*GetBlockInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlocksService_BlockValidators_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockValidatorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlocksServiceServer).BlockValidators(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlocksService_BlockValidators_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlocksServiceServer).BlockValidators(ctx, req.(*GetBlockValidatorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlocksService_TxChartByDay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxChartByDayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlocksServiceServer).TxChartByDay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlocksService_TxChartByDay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlocksServiceServer).TxChartByDay(ctx, req.(*TxChartByDayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlocksService_TxByHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxByHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlocksServiceServer).TxByHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlocksService_TxByHash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlocksServiceServer).TxByHash(ctx, req.(*TxByHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlocksService_TotalTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TotalTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlocksServiceServer).TotalTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlocksService_TotalTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlocksServiceServer).TotalTransactions(ctx, req.(*TotalTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BlocksService_ServiceDesc is the grpc.ServiceDesc for BlocksService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlocksService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "blocks.BlocksService",
	HandlerType: (*BlocksServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BlockInfo",
			Handler:    _BlocksService_BlockInfo_Handler,
		},
		{
			MethodName: "BlockValidators",
			Handler:    _BlocksService_BlockValidators_Handler,
		},
		{
			MethodName: "TxChartByDay",
			Handler:    _BlocksService_TxChartByDay_Handler,
		},
		{
			MethodName: "TxByHash",
			Handler:    _BlocksService_TxByHash_Handler,
		},
		{
			MethodName: "TotalTransactions",
			Handler:    _BlocksService_TotalTransactions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blocks.proto",
}
