// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Defiant Labs",
            "url": "https://defiantlabs.net/",
            "email": "info@defiantlabs.net"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/events.csv": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/csv"
                ],
                "parameters": [
                    {
                        "description": "The options for the POST body",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.TaxableEventsCSVRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/events.json": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "description": "The options for the POST body",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.TaxableEventsCSVRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/gcphealth": {
            "get": {
                "responses": {}
            }
        }
    },
    "definitions": {
        "main.TaxableEventsCSVRequest": {
            "type": "object",
            "properties": {
                "addresses": {
                    "type": "string"
                },
                "chain": {
                    "type": "string"
                },
                "endDate": {
                    "description": "can be null",
                    "type": "string"
                },
                "format": {
                    "type": "string"
                },
                "startDate": {
                    "description": "can be null",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Cosmos Tax CLI",
	Description:      "An API to interact with the Cosmos Tax CLI backend.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
